export const DialogConstants = {
    actions: {
        CONFIRMATION_DIALOG_OPEN: "OPEN_CONFIRMATION_DIALOG",
        CONFIRMATION_DIALOG_CLOSE: "CLOSE_CONFIRMATION_DIALOG",
        CONFIRMATION_DIALOG_CLOSED: "CONFIRMATION_DIALOG_CLOSED",

        SESSION_DIALOG_OPEN: "OPEN_SESSION_DIALOG",
        SESSION_DIALOG_CLOSE: "CLOSE_SESSION_DIALOG"
    }
}